version: '3.5'

volumes:
  wordpress_vol:
  mariadb_vol:
networks:
  wpsite:
    name: wpsite


services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_HOST=${DB_HOST}
    tty: true
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    env_file:
      .env
    networks:
      - wpsite
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 50s
      retries: 10
    
  wordpress:
    depends_on:
      mariadb: 
        condition: service_healthy
    build: ./requirements/wordpress/
    container_name: wordpress
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    env_file:
      .env
    networks:
      - wpsite

  nginx:
    depends_on:
      - mariadb 
      - wordpress
    build: ./requirements/nginx/
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    ports:
      - "443:443"
    networks:
      - wpsite

  redis:
    depends_on:
      - mariadb 
      - wordpress
    build: ./requirements/redis/
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    ports:
      - "6379:6379"
    networks:
      - wpsite

