version: '3.5'

volumes:
  wordpress_vol:
  mariadb_vol:
networks:
  wpsite:
    name: wpsite
    driver: bridge


services:
  mariadb:
    build: ./mariadb/
    tty: true
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    env_file:
      .env
    networks:
      - wpsite
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 50s
      retries: 10
    
  wordpress:
    depends_on:
      mariadb: 
        condition: service_healthy
    build: ./wordpress/
    container_name: wordpress
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    env_file:
      .env
    networks:
      - wpsite

  nginx:
    depends_on:
      - mariadb 
      - wordpress
    build: ./nginx
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    ports:
      - "443:443"
    networks:
      - wpsite

