version: '3'

volumes:
  mariadb_vol:

services:
  mariadb:
    build: ./mariadb/
    container_name: mariadb
    tty: true
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadb_vol:/var/lib/mysql
