version: '3'

volumes:
  mariadb_vol:
  wordpress_vol:
networks:
  wpsite:

services:
  mariadb:
    build: ./mariadb/
    container_name: mariadb
    tty: true
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: wp_data
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: a
    networks:
      - wpsite
    
  wordpress:
    depends_on:
      - mariadb
    build: ./wordpress/
    container_name: wordpress
    tty: true
    volumes:
      - wordpress_vol:/var/www/html
    restart: always
    command: rm /var/www/html/index.html && cp /usr/share/wordpress/* /var/www/html
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: a
      WORDPRESS_DB_NAME: wp_data
    networks:
      - wpsite
