up:
	@sudo docker compose up

build:
	@sudo docker compose build

down:
	@sudo docker compose down

stop:
	@sudo docker compose stop

rm:
	@sudo docker compose rm

connect:
	@sudo mysql -h 127.0.0.1 -P 3306 -u wp_user -pa wp_data

clean:
	@sudo docker system prune -af

fclean:
	@sudo docker system prune -f --volumes -a
